// Generates the sample bills for the CA check (Phase 4 exit criterion 4).
// Run: flutter test tool/ca_sample_bills_test.dart
// Output: ../../docs/ca-sample-bills/*.pdf and sheet.md
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:khata_core/khata_core.dart';
import 'package:mandi_khata_app/features/khata/data/statement_pdf.dart';
import 'package:mandi_khata_app/features/shop_sales/domain/shop_sale.dart';
import 'package:mandi_khata_app/features/shop_sales/presentation/invoice_actions.dart';
import 'package:mandi_khata_app/l10n/generated/app_localizations.dart';
import 'package:pdf/widgets.dart' as pw;

pw.Font _font(String file) => pw.Font.ttf(
  ByteData.sublistView(
    File('../../packages/mk_ui/assets/fonts/$file').readAsBytesSync(),
  ),
);

class _Item {
  const _Item(
    this.name,
    this.hsn,
    this.rateBp,
    this.qtyMilli,
    this.price, [
    this.discount = Money.zero,
  ]);
  final String name;
  final String hsn;
  final int rateBp;
  final int qtyMilli;
  final Money price;
  final Money discount;
}

class _Case {
  const _Case(
    this.no,
    this.title,
    this.items, {
    this.interState = false,
    this.gstin,
    this.customer,
    this.pos = '03',
    this.invoiceDiscount = const InvoiceDiscount.none(),
  });
  final String no;
  final String title;
  final List<_Item> items;
  final bool interState;
  final String? gstin;
  final String? customer;
  final String pos;
  final InvoiceDiscount invoiceDiscount;
}

const _cases = [
  _Case(
    'SI-W1-0001',
    'B2B intra-state (Punjab to Punjab), 5% and 18%',
    [
      _Item('DAP 50 kg', '3105', 500, 10000, Money(135000)),
      _Item('Neem oil 1 ltr', '3808', 1800, 5000, Money(35000)),
    ],
    gstin: '03AAPFU0939F1ZV',
    customer: 'Kisan Traders',
  ),
  _Case(
    'SI-W1-0002',
    'B2B inter-state (Haryana buyer, IGST)',
    [_Item('Urea 45 kg', '3102', 500, 20000, Money(26700))],
    interState: true,
    gstin: '06AAACH7409R1ZZ',
    customer: 'Haryana Agro',
    pos: '06',
  ),
  _Case('SI-W1-0003', 'B2C walk-in, cash, 12% pesticide', [
    _Item('Imidacloprid 100 ml', '3808', 1200, 3000, Money(45000)),
  ], customer: 'Walk-in'),
  _Case(
    'SI-W1-0004',
    'Line discount + 10% invoice discount, 5% and 12%',
    [
      _Item('Wheat seed 40 kg', '1001', 500, 5000, Money(240000), Money(12000)),
      _Item('Sprayer pump', '8424', 1200, 1000, Money(185000)),
    ],
    customer: 'Gurmeet Singh',
    invoiceDiscount: InvoiceDiscount.percent(1000),
  ),
];

void main() {
  setUpAll(initializeDateFormatting);

  test('write CA sample bills', () async {
    final fonts = StatementFonts(
      regular: _font('IBMPlexSans-Regular.ttf'),
      bold: _font('IBMPlexSans-SemiBold.ttf'),
      fallback: [
        _font('NotoSansDevanagari-Regular.ttf'),
        _font('NotoSansGurmukhi-Regular.ttf'),
      ],
    );
    final out = Directory('../../docs/ca-sample-bills')
      ..createSync(recursive: true);
    final sheet = StringBuffer('''
# Sample bills for the CA (Phase 4 exit criterion 4)

Generated by `apps/mandi_khata_app/tool/ca_sample_bills_test.dart`. Prices are
GST-inclusive (`shop.prices_include_gst` default). The business is
"Gupta Kisan Seva Kendra", GSTIN 03AAPFU0939F1ZV (sample data, not real).
For each bill please check: taxable value, rate per line, CGST/SGST vs IGST,
round-off, total, HSN and place of supply.

''');
    for (final c in _cases) {
      final t = SaleCalculator.compute(
        lines: [
          for (final (i, it) in c.items.indexed)
            CartLine(
              productId: 'p$i',
              name: it.name,
              qtyMilli: it.qtyMilli,
              unitPrice: it.price,
              lineDiscount: it.discount,
              rateBp: it.rateBp,
              hsn: it.hsn,
            ),
        ],
        mode: GstMode(interState: c.interState),
        discount: c.invoiceDiscount,
      );
      final total = t.beforeRoundOff + t.roundOff;
      final detail = SaleDetail(
        sale: SaleRecord(
          id: c.no,
          saleNo: c.no,
          entryDate: LedgerDate(2027, 4, 30),
          customerName: c.customer,
          customerGstin: c.gstin,
          placeOfSupply: c.pos,
          subtotal: t.subtotal,
          lineDiscounts: t.lineDiscounts,
          invoiceDiscount: t.invoiceDiscount,
          invoiceDiscountPct: 0,
          gst: t.gst,
          roundOff: t.roundOff,
          total: total,
          paidCash: total,
          paidUpi: Money.zero,
          paidCredit: Money.zero,
          status: SaleStatus.posted,
          createdAt: DateTime.utc(2027, 4, 30),
        ),
        lines: [
          for (final (i, r) in t.lines.indexed)
            InvoiceLine(
              id: '${c.no}-$i',
              lineNo: i,
              productId: 'p$i',
              productName: c.items[i].name,
              qtyMilli: c.items[i].qtyMilli,
              unitPrice: c.items[i].price,
              discount: c.items[i].discount + r.invoiceDiscountShare,
              split: r.split,
              unitCost: Money.zero,
              rateBp: c.items[i].rateBp,
              hsn: c.items[i].hsn,
            ),
        ],
      );
      final bytes = await SaleInvoices.build(
        detail,
        l10n: lookupAppLocalizations(const Locale('en')),
        languageCode: 'en',
        fonts: fonts,
        businessName: 'Gupta Kisan Seva Kendra',
        businessGstin: '03AAPFU0939F1ZV',
      );
      File('${out.path}/${c.no}.pdf').writeAsBytesSync(bytes);
      String m(Money v) => v.format(paise: PaiseDisplay.always);
      sheet
        ..writeln('## ${c.no}: ${c.title}')
        ..writeln()
        ..writeln('| Item | HSN | Rate | Qty | Price (incl.) | Taxable | Tax |')
        ..writeln('|---|---|---|---|---|---|---|');
      for (final (i, r) in t.lines.indexed) {
        final it = c.items[i];
        sheet.writeln(
          '| ${it.name} | ${it.hsn} | ${it.rateBp / 100}% | '
          '${it.qtyMilli / 1000} | ${m(it.price)} | '
          '${m(r.split.taxable)} | '
          '${m(r.split.cgst + r.split.sgst + r.split.igst)} |',
        );
      }
      sheet
        ..writeln()
        ..writeln(
          'Subtotal ${m(t.subtotal)}; line discounts '
          '${m(t.lineDiscounts)}; invoice discount ${m(t.invoiceDiscount)}; '
          'taxable ${m(t.gst.taxable)}; CGST ${m(t.gst.cgst)}; '
          'SGST ${m(t.gst.sgst)}; IGST ${m(t.gst.igst)}; '
          'round-off ${m(t.roundOff)}; **total ${m(total)}**.',
        )
        ..writeln();
    }
    sheet.writeln('''
## Return (credit note)

The app has no printable credit note yet (a return restocks the original
batch and credits khata or cash; see `ReturnRules`). Please check the return
logic on bill SI-W1-0001: returning 2 bags of DAP refunds 2 x 1,350.00 =
2,700.00 incl. 5% GST (taxable 2,571.43, CGST 64.28, SGST 64.29).
''');
    File('${out.path}/sheet.md').writeAsStringSync(sheet.toString());
  });
}
