import 'package:khata_core/khata_core.dart';
import 'package:mandi_khata_app/l10n/generated/app_localizations.dart';

/// Translates the English column titles khata_core and the shop report
/// tables use as keys; an unknown title stays English.
ReportTitle shopReportTitles(AppLocalizations l) {
  final map = <String, String>{
    'Product': l.shrColProduct,
    'Qty': l.shrColQty,
    'Revenue': l.shrColRevenue,
    'Cost': l.shrColCost,
    'Profit': l.shrColProfit,
    'Margin': l.shrColMargin,
    'Total': l.shrColTotal,
    'Supplier': l.shrColSupplier,
    'Unpaid bills': l.shrColUnpaidBills,
    'Due date': l.shrColDueDate,
    'Days overdue': l.shrColDaysOverdue,
    'Khata balance': l.shrColKhataBalance,
    'Customer': l.shrColCustomer,
    'Shop sales': l.shrColShopSales,
    'Shop returns': l.shrColShopReturns,
    'To collect': l.shrColToCollect,
    'Expired': l.shrColExpired,
    'Within 30 days': l.shrColWithin30Days,
    '31 to 60 days': l.shrCol31To60Days,
    '61 to 90 days': l.shrCol61To90Days,
    'Later': l.shrColLater,
    'Batch': l.shrColBatch,
    'Expiry': l.shrColExpiry,
    'Days left': l.shrColDaysLeft,
    'Status': l.shrColStatus,
    'Value at cost': l.shrColValueAtCost,
    'In stock': l.shrColInStock,
    'Reorder level': l.shrColReorderLevel,
    'Sold in 30 days': l.shrColSoldIn30Days,
    'Days of stock': l.shrColDaysOfStock,
    'Suggested purchase': l.shrColSuggestedPurchase,
    'Credit note': l.shrColCreditNote,
    'Invoice no': l.shrColInvoiceNo,
    'Date': l.shrColDate,
    'GSTIN': l.shrColGstin,
    'Type': l.shrColType,
    'Taxable value': l.shrColTaxableValue,
    'CGST': l.shrColCgst,
    'SGST': l.shrColSgst,
    'IGST': l.shrColIgst,
    'Invoice value': l.shrColInvoiceValue,
    'Place of supply': l.shrColPlaceOfSupply,
    'Rate %': l.shrColRate,
    'Credit note no': l.shrColCreditNoteNo,
    'HSN': l.shrColHsn,
    'Unit': l.shrColUnit,
    'Total value': l.shrColTotalValue,
    'Nature of document': l.shrColNatureOfDocument,
    'From': l.shrColFrom,
    'To': l.shrColTo,
    'Walk-in': l.shrColWalkIn,
  };
  return (english) => map[english] ?? english;
}
